<?php
	function notificationCodeMatch($BaseCode) {
		$aCodes = code_load('goodsInformationNoticeCode_1st');
		foreach ($aCodes as $key => $data) {
			$notificationCode[$data['codecd']] = $data['value'];
		}
		if ( ! $notificationCode){
			$notificationCode[0]			= "N1";		//의류
			$notificationCode[1]			= "N2";		//구두/신발
			$notificationCode[2]			= "N3";		//가방
			$notificationCode[3]			= "N4";		//패션잡화(모자/벨트/액세서리)
			$notificationCode[4]			= "N5";		//침구류/커튼
			$notificationCode[5]			= "N6";		//가구(침대/소파/싱크대/DIY제품)
			$notificationCode[6]			= "N7";		//영상가전(TV류)
			$notificationCode[7]			= "N8";		//가정용 전기제품(냉장고/세탁기/식기세척기/전자레인지)
			$notificationCode[8]			= "N9";		//계절가전(에어컨/온풍기)
			$notificationCode[9]			= "N10";	//사무용기기(컴퓨터/노트북/프린터)
			$notificationCode[10]			= "N11";	//광학기기(디지털카메라/캠코더)
			$notificationCode[11]			= "N12";	//소형전자(MP3/전자사전 등)
			$notificationCode[12]			= "N13";	//휴대폰
			$notificationCode[13]			= "N14";	//내비게이션
			$notificationCode[14]			= "N15";	//자동차용품(자동차부품/기타 자동차용품)
			$notificationCode[15]			= "N16";	//의료기기
			$notificationCode[16]			= "N17";	//주방용품
			$notificationCode[17]			= "N18";	//화장품
			$notificationCode[18]			= "N19";	//귀금속/보석/시계류
			$notificationCode[19]			= "N20";	//농축수산물
			$notificationCode[20]			= "N21";	//가공식품
			$notificationCode[21]			= "N22";	//건강기능식품
			$notificationCode[22]			= "N23";	//영유아용품
			$notificationCode[23]			= "N24";	//악기
			$notificationCode[24]			= "N25";	//스포츠용품
			$notificationCode[25]			= "N26";	//서적
			$notificationCode[26]			= "N27";	//호텔/펜션 예약
			$notificationCode[27]			= "N28";	//여행상품
			$notificationCode[28]			= "N29";	//항공권
			$notificationCode[29]			= "N30";	//자동차 대여 서비스(렌터카)
			$notificationCode[30]			= "N31";	//물품대여 서비스 (정수기, 비데, 공기청정기 등)
			$notificationCode[31]			= "N32";	//물품대여 서비스 (서적, 유아용품, 행사용품 등)
			$notificationCode[32]			= "N33";	//디지털 콘텐츠 (음원, 게임, 인터넷강의 등)
			$notificationCode[33]			= "N34";	//상품권/쿠폰
			$notificationCode[34]			= "N36";	//모바일쿠폰
			$notificationCode[35]			= "N37";	//영화/공연
			$notificationCode[36]			= "N38";	//기타 용역
			$notificationCode[37]			= "N35";	//기타 재화
			$notificationCode[38]			= "N39";	//생활화학제품
			$notificationCode[39]			= "N40";	//살생물제품
		}
		return $notificationCode[$BaseCode];
	}

	function notificationDetail($mode = 'forView') {
		$aCodes = code_load('goodsInformationNoticeCode_2st');
		foreach ($aCodes as $key => $data) {
			$notificationDetail[$data['codecd']] = $data['value'];
		}
		if( ! $notificationDetail){
			$notificationDetail['D1']		= '품명 및 모델명';
			$notificationDetail['D2']		= '색상';
			$notificationDetail['D3']		= '소재';
			$notificationDetail['D4']		= '여행사';
			$notificationDetail['D5']		= '유효기간';
			$notificationDetail['D6']		= '재질';
			$notificationDetail['D8_1']		= '제조자,수입품의 경우 수입자를 함께 표기';
			$notificationDetail['D8_2']		= '제조자';
			$notificationDetail['D9_1']		= '제조업소의 명칭과 소재지(수입품의 경우 수입업소명, 제조업소명 및 수출국명)';
			$notificationDetail['D9_2']		= '제조국 또는 원산지';
			$notificationDetail['D9_3']		= '원산지'; //Old
			$notificationDetail['D16']		= '농수산물의 원산지 표시에 관한 법률에 따른 원산지';
			$notificationDetail['D10']		= '종류';
			$notificationDetail['D11']		= '차종';
			$notificationDetail['D13']		= '크기';
			$notificationDetail['D14']		= '중량';
			$notificationDetail['D15']		= '제품구성';
			$notificationDetail['D17_1']	= '사용연령 또는 체중범위';
			$notificationDetail['D17_2']	= '사용연령';	//Old	
			$notificationDetail['D18']		= '구성품';
			$notificationDetail['D19']		= '적용차종';
			$notificationDetail['D20']		= '관람등급';
			$notificationDetail['D21']		= '주연';
			$notificationDetail['D22']		= '도서명';
			$notificationDetail['D23']		= '쪽수';
			$notificationDetail['D24']		= '출간일';
			$notificationDetail['D25']		= '등급, 객실타입';
			$notificationDetail['D26']		= '관련법상 표시사항';
			$notificationDetail['D27']		= '기능정보';
			$notificationDetail['D28']		= '냉난방면적';
			$notificationDetail['D29']		= '맵 업데이트 비용 및 무상기간';
			$notificationDetail['D30']		= '발행자';
			$notificationDetail['D31']		= '배송/설치 비용';
			$notificationDetail['D32_1']	= '법에 의한 인증,허가 등을 받았음을 확인할수 있는 경우 그에 대한 사항';
			$notificationDetail['D32_2']	= '법에 의한 인증 허가';
			$notificationDetail['D33']		= '보관방법 또는 취급방법';
			$notificationDetail['D34']		= '보증서 제공여부';
			$notificationDetail['D35']		= '부대시설, 제공서비스';
			$notificationDetail['D36']		= '사용가능 인원, 인원 추가시 비용';
			$notificationDetail['D37_1']	= '사용기한 또는 개봉 후 사용기간';
			$notificationDetail['D37_2']	= '사용기한';
			$notificationDetail['D38']		= '사용방법';
			$notificationDetail['D39']		= '사용할 때 주의사항';
			$notificationDetail['D40']		= '상품제공방식';
			$notificationDetail['D41']		= '상품구성';
			$notificationDetail['D42']		= '상품별 세부 사양';
			$notificationDetail['D43']		= '상품의 고장,분실,훼손시 소비자 책임';
			$notificationDetail['D44_1']	= '섭취량,섭취방법 및 섭취시 주의사항 및 부작용 가능성';
			$notificationDetail['D44_2']	= '부작용 발생 가능성';	//Old
			$notificationDetail['D44_3']	= '섭취량,섭취방법 및 섭취시 주의사항';	//Old
			$notificationDetail['D45']		= '세탁방법 및 취급시 주의사항';
			$notificationDetail['D46']		= '소비자상담관련 전화번호';
			$notificationDetail['D47']		= '소유권 이전 조건';
			$notificationDetail['D48']		= '소재/순도/밴드재질';
			$notificationDetail['D49']		= '숙박정보';
			$notificationDetail['D50']		= '숙소형태';
			$notificationDetail['D52']		= '식품의 유형';
			$notificationDetail['D53_1']	= '기능성 화장품의 경우 화장품법에 따른 식품의약안전청 심사 필 유무';
			$notificationDetail['D53_2']	= '식품의약품안전청 심사 필 유무';	//Old
			$notificationDetail['D54']		= '여행기간 및 일정';
			$notificationDetail['D55_1']	= '영양성분(식품 등의 표시·광고에 관한 법률에 따른 영양성분 표시대상 식품에 한함)';
			$notificationDetail['D55_2']	= '영양성분';	//Old
			$notificationDetail['D56']		= '영양정보';
			$notificationDetail['D57']		= '영유아식 또는 체중조절식품 등에 해당하는 경우 표시광고 사전심의필';
			$notificationDetail['D58']		= '예약 취소 또는 중도 해약시 환불 기준';
			$notificationDetail['D59']		= '예약담당 연락처';
			$notificationDetail['D60']		= '해외여행의 경우 외교통상부가 지정하는 여행경보단계';
			$notificationDetail['D61']		= '요금조건, 왕복,편도 여부';
			$notificationDetail['D62_1']	= '용량 및 중량';
			$notificationDetail['D62_2']	= '용량 또는 중량';	//Old
			$notificationDetail['D63']		= '원재료명 및 함량';
			$notificationDetail['D64_1']	= '유전자변형식품에 해당하는 경우의 표시';
			$notificationDetail['D64_2']	= '유전자재조합식품에 해당하는 경우의 표시';	//Old
			$notificationDetail['D65']		= '유전자변형건강기능식품에 해당하는 경우의 표시';
			$notificationDetail['D66']		= '유지보수 조건';
			$notificationDetail['D67_1']	= '유효기간, 이용조건 (이용방법 - 이용조건##유효기간)';
			$notificationDetail['D67_2']	= '유효기간, 이용조건';
			$notificationDetail['D68']		= '의료기기법상 허가,신고 번호';
			$notificationDetail['D69']		= '이동통신 가입조건';
			$notificationDetail['D70']		= '이용 가능 매장';
			$notificationDetail['D71']		= '이용조건, 이용기간';
			$notificationDetail['D72']		= '이용항공편';
			$notificationDetail['D73']		= '자동차관리법에 따른 자동차부품 자기인증 유무';
			$notificationDetail['D74']		= '잔액 환급 조건';
			$notificationDetail['D75_1']	= 'KC 인증 필 유무 - 전기용품';
			$notificationDetail['D75_2']	= '전기용품 안전인증 필 유무';
			$notificationDetail['D76_1']	= '정격전압,소비전력';
			$notificationDetail['D76_2']	= '정격전함, 소비전력';
			$notificationDetail['D77_1']	= '에너지소비효율등급';
			$notificationDetail['D77_2']	= '정격전압, 소비전력, 에너지소비효율등급';
			$notificationDetail['D78']		= '제조국';
			$notificationDetail['D80']		= '제조연월';
			$notificationDetail['D81_1']	= '제조연월일(포장일 또는 생산연도), 유통기한';
			$notificationDetail['D81_2']	= '제조연월일(조장일 또는 생산연도),유통기한 또는 품질유지기한';
			$notificationDetail['D82']		= '제품사양';
			$notificationDetail['D83']		= '제품소재';
			$notificationDetail['D84']		= '제품 주요 사양';
			$notificationDetail['D85']		= '제품의 사용목적 및 사용방법';
			$notificationDetail['D86']		= '제한사항';
			$notificationDetail['D87']		= '좌석종류';
			$notificationDetail['D88']		= '주요사양';
			$notificationDetail['D89']		= '주요소재';
			$notificationDetail['D90_1']	= '화장품법에 따라 기재,표시하여야 하는 모든성분';
			$notificationDetail['D90_2']	= '주요성분';	//Old
			$notificationDetail['D91']		= '중도 해약시 환불 기준';
			$notificationDetail['D92']		= '국가 또는 지역명';
			$notificationDetail['D93']		= '질병의 예방 및 치료를 위한 의약품이 아니라는 내용의 표현';
			$notificationDetail['D94']		= '차량 반환시 연료대금 정산방법';
			$notificationDetail['D95']		= '차량의 고장,훼손시 소비자 책임';
			$notificationDetail['D96']		= '착용시 주의사항';
			$notificationDetail['D97_1']	= '청약철회 또는 계약의 해제,해지에 따른 효과';
			$notificationDetail['D97_2']	= '청약철회/계약의 해제·해지에 따른 효과';	//Old	
			$notificationDetail['D98_1']	= '총 예정 인원, 출발 가능 인원';
			$notificationDetail['D98_2']	= '종 예정 인원, 출발 가능 인원';	//Old
			$notificationDetail['D99']		= '최소시스템사양, 필수 소프트웨어';
			$notificationDetail['D101']		= '추가 선택시 비용';
			$notificationDetail['D102']		= '추가설치비용';
			$notificationDetail['D103']		= '동일모델의 출시년월';
			$notificationDetail['D104']		= '취급시 주의사항';
			$notificationDetail['D105']		= '치수';
			$notificationDetail['D106']		= '취소규정';
			$notificationDetail['D107']		= '크기, 무게';
			$notificationDetail['D108']		= '크기, 중량 ';
			$notificationDetail['D109']		= '티켓수령방법';
			$notificationDetail['D110_1']	= '포장단위별 내용물의 용량(중량), 수량, 크기';
			$notificationDetail['D110_2']	= '포장단위별 용량(중량),수량,크기'; //Old
			$notificationDetail['D110_3']	= '크기(용량, 형태 포함)';	//Old
			$notificationDetail['D111_1']	= '포장단위별 내용물의 용량(중량), 수량';
			$notificationDetail['D111_2']	= '포장단위별 용량(중량),수량';	//Old
			$notificationDetail['D112']		= '여행상품 가격';
			$notificationDetail['D113']		= '표시광고 사전심의필';
			$notificationDetail['D114']		= '품질보증기준';
			$notificationDetail['D115']		= '화면사양';
			$notificationDetail['D117_1']	= 'AS책임자와 전화번호';
			$notificationDetail['D117_2']	= 'AS책임자와 전화번호 또는 소비자상담 관련 전화번호';
			$notificationDetail['D118']		= 'KC 인증 필 유무';
			$notificationDetail['D119']		= '어린이제품 안전 특별법 상 안전인증대상어린이제품, 안전확인대상어린이제품,공급자적합성 확인대상어린이제품에 대한 KC 인증 필 유무';
			$notificationDetail['D120_1']	= 'KC 인증 필 유무 - 정보통신기자재';
			$notificationDetail['D120_2']	= 'KCC 인증 필 유무';
			$notificationDetail['D121']		= '목차 또는 책소개';
			$notificationDetail['D122_1']	= '제품사용으로 인한 위험 및 유의사항(연료절감장치에한함)';
			$notificationDetail['D122_2']	= '제품 사용으로 인한 위험 및 유의사항';	//Old
			$notificationDetail['D123_1']	= '수입식품에 해당하는 경우 “수입식품안전관리특별법에 따른 수입신고를 필함”의 문구';
			$notificationDetail['D123_2']	= '수입식품에 해당하는 경우 건강기능식품에 따른 수입신고를 필함의 문구';	//Old
			$notificationDetail['D123_3']	= '수입식품에 해당하는 경우 식품위생법에 따른 수입신고를 필함의 문구';	//Old
			$notificationDetail['D123_4']	= '수입식품 인 경우 “식품위생법에 따른 수입신고를 필함”의 문구';	//Old
			$notificationDetail['D124']		= '제작자 또는 공급자';
			$notificationDetail['D125_1']	= '화장품제조업자 및 화장품책임판매업자';
			$notificationDetail['D125_2']	= '제조자 및 제조판매업자'; //Old
			$notificationDetail['D126']		= '품명';
			$notificationDetail['D127']		= '환불조건 및 방법';
			$notificationDetail['D128']		= '취소환불방법';
			$notificationDetail['D129']		= '예매취소 조건';
			$notificationDetail['D130']		= '상영,공연장소';
			$notificationDetail['D131']		= '상영,공연시간';
			$notificationDetail['D132']		= '이용조건';
			$notificationDetail['D133']		= '서비스 제공 사업자';
			$notificationDetail['D134']		= '주최 또는 기획';
			$notificationDetail['D135']		= '취소,중도해약,해지 조건 및 환불기준';
			$notificationDetail['D136']		= '취급방법 및 취급시 주의사항, 안전표시';
			$notificationDetail['D137']		= '제품 주소재';
			$notificationDetail['D138_1']	= '생산자,수입품의 경우 수입자를 함께 표기';
			$notificationDetail['D138_2']	= '생산자';	//Old
			$notificationDetail['D139_1']	= '수입식품안전관리특별법에 따른 수입 기구·용기의 경우 “수입식품안전관리특별법에 따른 수입신고를 필함”의 문구';
			$notificationDetail['D139_2']	= '식품위생법에 따른 수입 기구,용기의 경우 식품위생법에 따른 수입신고를 필함의 문구'; // Old
			$notificationDetail['D139_3']	= '수입신고필 유무';	// Old
			$notificationDetail['D140_1']	= '제조연월일, 유통기한';
			$notificationDetail['D140_2']	= '제조연월일, 유통기한 또는 품질유지기한';	//Old
			$notificationDetail['D140_3']	= '제조연월일(포장일 또는 생산연도), 유통기한 또는 품질유지기한';	//Old
			$notificationDetail['D140']		= '제조년월';
			$notificationDetail['D142_1']	= '추가 경비 항목과 금액';
			$notificationDetail['D142_2']	= '선택경비 유무 등';
			$notificationDetail['D144']		= '이동통신사';
			$notificationDetail['D145']		= '가입절차';
			$notificationDetail['D146']		= '소비자의 추가적인 부담사항';
			$notificationDetail['D147_1']	= '생산자 및 소재지, 수입품의 경우 생산자, 수입자 및 제조국 함께 표기';
			$notificationDetail['D147_2']	= '생산자 및 소재지';	// Old
			$notificationDetail['D147_3']	= '생산자 및 소재지, 수입품의 경우 수입자를 함께 표기';	//Old
			$notificationDetail['D149_1']	= '저자, 출판사';
			$notificationDetail['D149_2']	= '저자'; //Old
			$notificationDetail['D150_1']	= '귀금속,보석류-등급';
			$notificationDetail['D150_2']	= '주요 사양 -> 귀금속,보석류-등급';
			$notificationDetail['D151']		= '시계-기능,방수';
			$notificationDetail['D152_1']	= '농산물-농산물품질관리법상 유전자변형농산물 표시, 지리적표시';
			$notificationDetail['D152_2']	= '수산물-수산물품질관리법상 유전자변형수산물 표시, 지리적표시';
			$notificationDetail['D152_3']	= '농산물-농산물품질관리 법사 유전자 변형 농산물 표시, 지리적표시';	//Old
			$notificationDetail['D153_1']	= '축산물 – 축산법에 따른 등급 표시, 축산물이력법에 따른 이력관리대상축산물 유무';
			$notificationDetail['D153_2']	= '축산물-축산법에 따른 등급표시, 쇠고기의 경우 이력관리에 따른 표시 유무';	//Old
			$notificationDetail['D154']		= '선택관광 및 대체일정';
			$notificationDetail['D155']		= '가이드 팁';
			$notificationDetail['D156']		= '검사합격증 번호';
			$notificationDetail['D157']		= '품목 또는 명칭';
			$notificationDetail['D158']		= '식품 등의 표시·광고에 관한 법률에 따른 소비자안전을 위한 주의사항';
			$notificationDetail['D159']		= '제품명';
			$notificationDetail['D160']		= '소비자안전을 위한 주의사항';
			$notificationDetail['D161']		= '품목 및 제품명';
			$notificationDetail['D162']		= '용도(표백제의 경우 계열을 함께 표시) 및 제형';
			$notificationDetail['D163']		= '제조연월 및 유통기한(해당 없는 제품 생략 가능)';
			$notificationDetail['D164']		= '중량․용량․매수';
			$notificationDetail['D165']		= '효과․효능(승인대상 제품에 한함)';
			$notificationDetail['D166']		= '수입자(수입제품에 한함), 제조국 및 제조사';
			$notificationDetail['D167']		= '어린이 보호포장 대상 제품 유무';
			$notificationDetail['D168']		= '제품에 사용된 화학물질 명칭(주요물질, 보존제 등 관련 고시에 따른 표시의무 화학물질에 한함)';
			$notificationDetail['D169']		= '사용상 주의사항';
			$notificationDetail['D170']		= '안전기준 적합확인 신고번호(자가검사번호) 또는 안전확인대상 생활화학제품 승인번호';
			$notificationDetail['D171']		= '소비자 상담관련 전화번호';
			$notificationDetail['D172']		= '제품명 및 제품유형';
			$notificationDetail['D173']		= '중량 또는 용량 및 표준사용량';
			$notificationDetail['D174']		= '효과․효능';
			$notificationDetail['D175']		= '제품명 및 제품유형';
			$notificationDetail['D176']		= '사용대상자 및 사용범위';
			$notificationDetail['D177']		= '어린이보호포장 대상제품 유무';
			$notificationDetail['D178']		= '살생물물질, 나노물질, 기타 화학물질(유해화학물질 또는 중점관리물질)의 명칭';
			$notificationDetail['D179']		= '제품 유해성․위해성 표시';
			$notificationDetail['D180']		= '사용방법 및 사용상 주의사항';
			$notificationDetail['D181']		= '승인번호';
		}
		
		if ($mode == 'forSearch') {
			$return		= array();
			foreach ($notificationDetail as $key => $val)
				$return[$key]		= makeTextForSearch($val);
			
			return $return;
		} else {
			return $notificationDetail;
		}
	}



	function makeTextForSearch($inText) {
		$searchText		= trim(preg_replace('/[^a-zA-Z|^\x{ac00}-\x{d7af}]/u', '', $inText));
		$searchKey		= md5($searchText);
		return $searchKey;
	}
