<?php

namespace App\Libraries;

/**
 * 카카오톡구매 및 클레임 처리시 사용되는 interface 목록
 */
interface TalkbuyInterface {
    // claimProcessType
    const CPT_CANCEL_REQUEST = "CANCEL_REQUEST";
    const CPT_CANCEL_DONE = "CANCEL_DONE";
    const CPT_CANCEL_REJECT = "CANCEL_REJECT";
    const CPT_CANCEL_REFUND_FAILED = "CANCEL_REFUND_FAILED";
    const CPT_CANCEL_WAIT_REFUND_SAVING = "CANCEL_WAIT_REFUND_SAVING";
    const CPT_CANCEL_REFUND_BANK_ACCOUNT = "CANCEL_REFUND_BANK_ACCOUNT";
    const CPT_RETURN_REQUEST = "RETURN_REQUEST";
    const CPT_RETURN_BACKWARD_DELIVERY = "RETURN_BACKWARD_DELIVERY";
    const CPT_RETURN_BACKWARD_DELIVERY_DONE = "RETURN_BACKWARD_DELIVERY_DONE";
    const CPT_RETURN_DONE = "RETURN_DONE";
    const CPT_RETURN_REFUND_FAILED = "RETURN_REFUND_FAILED";
    const CPT_RETURN_WAIT_REFUND_SAVING = "RETURN_WAIT_REFUND_SAVING";
    const CPT_RETURN_HOLDBACK = "RETURN_HOLDBACK";
    const CPT_RETURN_REJECT = "RETURN_REJECT";
    const CPT_RETURN_BACKWARD_DELIVERY_CHECKING = "RETURN_BACKWARD_DELIVERY_CHECKING";
    const CPT_EXCHANGE_REQUEST = "EXCHANGE_REQUEST";
    const CPT_EXCHANGE_BACKWARD_DELIVERY = "EXCHANGE_BACKWARD_DELIVERY";
    const CPT_EXCHANGE_BACKWARD_DELIVERY_DONE = "EXCHANGE_BACKWARD_DELIVERY_DONE";
    const CPT_EXCHANGE_FORWARD_DELIVERY = "EXCHANGE_FORWARD_DELIVERY";
    const CPT_EXCHANGE_REFUND_FAILED = "EXCHANGE_REFUND_FAILED";
    const CPT_EXCHANGE_WAIT_REFUND_SAVING = "EXCHANGE_WAIT_REFUND_SAVING";
    const CPT_EXCHANGE_HOLDBACK = "EXCHANGE_HOLDBACK";
    const CPT_EXCHANGE_DONE = "EXCHANGE_DONE";
    const CPT_EXCHANGE_REJECT = "EXCHANGE_REJECT";

    // ClaimType
    const CT_CANCEL = "CANCEL";
    const CT_RETURN = "RETURN";
    const CT_EXCHANGE = "EXCHANGE";

    // requester
    const REQ_SELLER = "SELLER";
    const REQ_PURCHASER = "PURCHASER";
    const REQ_ADMIN = "ADMIN";
    const REQ_BATCH = "BATCH";

    //personInChargeType
    const PERSON_ICT_SELLER = "SELLER";
    const PERSON_ICT_PURCHASER = "PURCHASER";

    //claimShippingFeePayMet
    const SHIP_FEE_PREPAID = "PREPAID";
    const SHIP_FEE_DEDUCTED = "DEDUCTED";
    const SHIP_FEE_DELEGATED_TO_SELLER = "DELEGATED_TO_SELLER";
    const SHIP_FEE_INCLUDED_ON_RETURN = "INCLUDED_ON_RETURN";

    const KAKAO_PG = "talkbuy";

    //collectMethodType
    const CMT_DELIVERY_ALREADY = "DELIVERY_ALREADY";
    const CMT_DELIVERY_BY_CHECKOUT = "DELIVERY_BY_CHECKOUT";
    const CMT_DELIVERY_INDIVIDUAL = "DELIVERY_INDIVIDUAL";
}
